import type { ExerciseDef } from "./types";

/**
 * Canonical exercise catalog. Seeded into the database (see DATA_MODEL.md §2) and used in-memory by
 * the WOD parser/analyzer. Keep ids stable: they are foreign keys.
 *
 * Aliases are lowercase; the resolver normalises input (accents, punctuation, plurals) before lookup.
 */
const c = (
  lower: number,
  upper: number,
  cardio: number,
): ExerciseDef["cost"] => ({ lower, upper, cardio });

export const EXERCISE_CATALOG: readonly ExerciseDef[] = [
  // ---------------------------------------------------------------------------
  // Barbell — squat
  // ---------------------------------------------------------------------------
  {
    id: "back_squat",
    name: "Back squat",
    aliases: ["back squat", "bs", "squat", "squat arrière", "squat barre", "high bar squat", "low bar squat"],
    category: "barbell",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "lower_back", "core", "adductors"],
    equipment: ["barbell", "rack"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 2,
    isBenchmarkLift: true,
    cost: c(3, 0.5, 1),
  },
  {
    id: "front_squat",
    name: "Front squat",
    aliases: ["front squat", "fs", "squat avant", "squat clavicule"],
    category: "barbell",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core", "upper_back", "adductors"],
    equipment: ["barbell", "rack"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 2,
    isBenchmarkLift: true,
    cost: c(3, 1, 1),
  },
  {
    id: "overhead_squat",
    name: "Overhead squat",
    aliases: ["overhead squat", "ohs", "squat overhead", "squat bras tendus"],
    category: "barbell",
    movementPattern: "squat",
    secondaryPatterns: ["vertical_push"],
    primaryMuscles: ["quads", "glutes", "shoulders"],
    secondaryMuscles: ["core", "upper_back", "traps"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 5,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2.5, 1.5, 1),
  },
  {
    id: "goblet_squat",
    name: "Goblet squat",
    aliases: ["goblet squat", "kb squat", "kettlebell squat", "goblet"],
    category: "kettlebell",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core"],
    equipment: ["kettlebell", "dumbbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2, 0.5, 1),
  },
  {
    id: "air_squat",
    name: "Air squat",
    aliases: ["air squat", "air squats", "squat pdc", "bodyweight squat", "squats au poids du corps"],
    category: "bodyweight",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 0,
    cost: c(1, 0, 1),
  },
  {
    id: "pistol",
    name: "Pistol squat",
    aliases: ["pistol", "pistols", "pistol squat", "single leg squat", "squat une jambe"],
    category: "gymnastics",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["core", "calves"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 4,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(2, 0, 1),
  },
  {
    id: "wall_ball",
    name: "Wall ball",
    aliases: ["wall ball", "wall balls", "wb", "wallball", "wallballs", "wall-ball", "wall ball shots"],
    category: "other",
    movementPattern: "squat",
    secondaryPatterns: ["vertical_push"],
    primaryMuscles: ["quads", "glutes", "shoulders"],
    secondaryMuscles: ["core", "triceps"],
    equipment: ["wall_ball"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(2, 1, 2),
  },
  {
    id: "thruster",
    name: "Thruster",
    aliases: ["thruster", "thrusters", "barbell thruster"],
    category: "barbell",
    movementPattern: "squat",
    secondaryPatterns: ["vertical_push"],
    primaryMuscles: ["quads", "glutes", "shoulders"],
    secondaryMuscles: ["triceps", "core", "upper_back"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2.5, 2, 3),
  },
  {
    id: "dumbbell_thruster",
    name: "Dumbbell thruster",
    aliases: ["dumbbell thruster", "db thruster", "db thrusters", "dumbbell thrusters", "thruster haltères"],
    category: "dumbbell",
    movementPattern: "squat",
    secondaryPatterns: ["vertical_push"],
    primaryMuscles: ["quads", "glutes", "shoulders"],
    secondaryMuscles: ["triceps", "core"],
    equipment: ["dumbbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2.5, 2, 3),
  },
  {
    id: "lunge",
    name: "Lunge",
    aliases: ["lunge", "lunges", "fente", "fentes", "walking lunge", "walking lunges", "fentes marchées", "reverse lunge", "front rack lunge", "overhead lunge", "db lunge", "dumbbell lunge", "barbell lunge"],
    category: "bodyweight",
    movementPattern: "squat",
    secondaryPatterns: ["locomotion"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "core", "adductors"],
    equipment: ["bodyweight", "dumbbell", "barbell"],
    measurementType: "reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 2,
    impactLevel: 1,
    eccentricLoad: 2,
    cost: c(2.5, 0.5, 1.5),
  },
  {
    id: "box_step_up",
    name: "Box step-up",
    aliases: ["box step up", "box step-up", "step up", "step-ups", "step ups", "box step ups", "montée de box", "db step up", "dumbbell step up", "weighted step up"],
    category: "bodyweight",
    movementPattern: "squat",
    secondaryPatterns: ["locomotion"],
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["box", "bodyweight", "dumbbell"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(2, 0.5, 1.5),
  },
  {
    id: "leg_press",
    name: "Leg press",
    aliases: ["leg press", "presse à cuisses", "presse"],
    category: "machine",
    movementPattern: "squat",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    measurementType: "weight_reps",
    defaultIncrementKg: 5,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(2.5, 0, 0.5),
  },
  {
    id: "leg_extension",
    name: "Leg extension",
    aliases: ["leg extension", "leg extensions", "leg ext"],
    category: "machine",
    movementPattern: "isolation",
    primaryMuscles: ["quads"],
    equipment: ["machine"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(1.5, 0, 0.3),
  },
  {
    id: "leg_curl",
    name: "Leg curl",
    aliases: ["leg curl", "leg curls", "hamstring curl", "ischio curl"],
    category: "machine",
    movementPattern: "isolation",
    primaryMuscles: ["hamstrings"],
    equipment: ["machine"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(1.5, 0, 0.3),
  },

  // ---------------------------------------------------------------------------
  // Hinge
  // ---------------------------------------------------------------------------
  {
    id: "deadlift",
    name: "Deadlift",
    aliases: ["deadlift", "deadlifts", "dl", "dead lift", "soulevé de terre", "sdt", "conventional deadlift"],
    category: "barbell",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes", "lower_back"],
    secondaryMuscles: ["quads", "upper_back", "traps", "forearms_grip", "core"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 2,
    isBenchmarkLift: true,
    cost: c(3, 1.5, 1),
  },
  {
    id: "sumo_deadlift",
    name: "Sumo deadlift",
    aliases: ["sumo deadlift", "sumo dl", "sumo"],
    category: "barbell",
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings", "adductors"],
    secondaryMuscles: ["quads", "lower_back", "upper_back", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(3, 1.5, 1),
  },
  {
    id: "romanian_deadlift",
    name: "Romanian deadlift",
    aliases: ["romanian deadlift", "rdl", "rdls", "sdt roumain", "stiff leg deadlift", "sldl", "db rdl", "dumbbell rdl", "dumbbell romanian deadlift"],
    category: "barbell",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "glutes"],
    secondaryMuscles: ["lower_back", "forearms_grip"],
    equipment: ["barbell", "dumbbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 3,
    cost: c(2.5, 1, 0.5),
  },
  {
    id: "good_morning",
    name: "Good morning",
    aliases: ["good morning", "good mornings", "gm"],
    category: "barbell",
    movementPattern: "hinge",
    primaryMuscles: ["hamstrings", "lower_back", "glutes"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 3,
    cost: c(2, 0.5, 0.5),
  },
  {
    id: "hip_thrust",
    name: "Hip thrust",
    aliases: ["hip thrust", "hip thrusts", "glute bridge", "barbell hip thrust"],
    category: "barbell",
    movementPattern: "hinge",
    primaryMuscles: ["glutes"],
    secondaryMuscles: ["hamstrings"],
    equipment: ["barbell", "bench"],
    measurementType: "weight_reps",
    defaultIncrementKg: 5,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2, 0, 0.5),
  },
  {
    id: "kettlebell_swing",
    name: "Kettlebell swing",
    aliases: ["kettlebell swing", "kb swing", "kb swings", "kettlebell swings", "swing", "swings", "russian swing", "american swing", "kbs"],
    category: "kettlebell",
    movementPattern: "hinge",
    primaryMuscles: ["glutes", "hamstrings"],
    secondaryMuscles: ["lower_back", "shoulders", "forearms_grip", "core"],
    equipment: ["kettlebell"],
    measurementType: "reps",
    defaultIncrementKg: 4,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(1.5, 1, 2),
  },
  {
    id: "back_extension",
    name: "Back extension",
    aliases: ["back extension", "back extensions", "hip extension", "hip extensions", "ghd back extension", "lombaires", "extensions lombaires"],
    category: "bodyweight",
    movementPattern: "hinge",
    primaryMuscles: ["lower_back", "glutes", "hamstrings"],
    equipment: ["ghd"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(1.5, 0, 0.5),
  },

  // ---------------------------------------------------------------------------
  // Olympic lifts (all count as olympic_lift with hinge/squat secondaries)
  // ---------------------------------------------------------------------------
  {
    id: "clean",
    name: "Clean",
    aliases: ["clean", "cleans", "squat clean", "squat cleans", "full clean", "épaulé"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "squat"],
    primaryMuscles: ["quads", "glutes", "hamstrings", "traps"],
    secondaryMuscles: ["upper_back", "core", "shoulders", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 5,
    impactLevel: 1,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(3, 1.5, 2),
  },
  {
    id: "power_clean",
    name: "Power clean",
    aliases: ["power clean", "power cleans", "pc", "épaulé debout"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings", "traps"],
    secondaryMuscles: ["quads", "upper_back", "core", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 4,
    impactLevel: 1,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(2.5, 1.5, 2),
  },
  {
    id: "hang_clean",
    name: "Hang clean",
    aliases: ["hang clean", "hang cleans", "hang squat clean"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "squat"],
    primaryMuscles: ["quads", "glutes", "hamstrings", "traps"],
    secondaryMuscles: ["upper_back", "core", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 4,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(2.5, 1.5, 2),
  },
  {
    id: "hang_power_clean",
    name: "Hang power clean",
    aliases: ["hang power clean", "hang power cleans", "hpc"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge"],
    primaryMuscles: ["glutes", "hamstrings", "traps"],
    secondaryMuscles: ["quads", "upper_back", "core", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(2, 1.5, 2),
  },
  {
    id: "clean_and_jerk",
    name: "Clean & jerk",
    aliases: ["clean and jerk", "clean & jerk", "c&j", "cj", "c and j", "épaulé jeté", "epaule jete", "clean and jerks", "clean & jerks"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "squat", "vertical_push"],
    primaryMuscles: ["quads", "glutes", "hamstrings", "shoulders", "traps"],
    secondaryMuscles: ["upper_back", "core", "triceps", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 5,
    impactLevel: 1,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(3, 2, 2.5),
  },
  {
    id: "snatch",
    name: "Snatch",
    aliases: ["snatch", "snatches", "squat snatch", "full snatch", "arraché"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "squat", "vertical_push"],
    primaryMuscles: ["quads", "glutes", "hamstrings", "shoulders", "traps"],
    secondaryMuscles: ["upper_back", "core", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 5,
    impactLevel: 1,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(2.5, 2, 2),
  },
  {
    id: "power_snatch",
    name: "Power snatch",
    aliases: ["power snatch", "power snatches", "ps", "arraché debout"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "vertical_push"],
    primaryMuscles: ["glutes", "hamstrings", "shoulders", "traps"],
    secondaryMuscles: ["quads", "upper_back", "core", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 4,
    impactLevel: 1,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(2, 2, 2),
  },
  {
    id: "hang_power_snatch",
    name: "Hang power snatch",
    aliases: ["hang power snatch", "hang power snatches", "hps", "hang snatch", "hang snatches"],
    category: "olympic",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "vertical_push"],
    primaryMuscles: ["glutes", "hamstrings", "shoulders", "traps"],
    secondaryMuscles: ["core", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 4,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(2, 2, 2),
  },
  {
    id: "clean_pull",
    name: "Clean pull",
    aliases: ["clean pull", "clean pulls", "tirage clean", "clean deadlift"],
    category: "olympic",
    movementPattern: "hinge",
    secondaryPatterns: ["olympic_lift"],
    primaryMuscles: ["hamstrings", "glutes", "traps"],
    secondaryMuscles: ["lower_back", "upper_back", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2.5, 1, 1),
  },
  {
    id: "snatch_pull",
    name: "Snatch pull",
    aliases: ["snatch pull", "snatch pulls", "tirage snatch", "snatch deadlift"],
    category: "olympic",
    movementPattern: "hinge",
    secondaryPatterns: ["olympic_lift"],
    primaryMuscles: ["hamstrings", "glutes", "traps"],
    secondaryMuscles: ["lower_back", "upper_back", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2.5, 1, 1),
  },
  {
    id: "sumo_deadlift_high_pull",
    name: "Sumo deadlift high pull",
    aliases: ["sumo deadlift high pull", "sdhp", "sumo high pull"],
    category: "barbell",
    movementPattern: "hinge",
    secondaryPatterns: ["vertical_pull"],
    primaryMuscles: ["glutes", "hamstrings", "traps", "shoulders"],
    secondaryMuscles: ["upper_back", "forearms_grip"],
    equipment: ["barbell", "kettlebell"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2, 1.5, 2),
  },
  {
    id: "dumbbell_snatch",
    name: "Dumbbell snatch",
    aliases: ["dumbbell snatch", "db snatch", "db snatches", "dumbbell snatches", "alternating dumbbell snatch", "alt db snatch", "snatch haltère"],
    category: "dumbbell",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "vertical_push"],
    primaryMuscles: ["glutes", "hamstrings", "shoulders"],
    secondaryMuscles: ["core", "traps", "forearms_grip"],
    equipment: ["dumbbell"],
    measurementType: "reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2, 1.5, 2.5),
  },
  {
    id: "dumbbell_clean",
    name: "Dumbbell clean",
    aliases: ["dumbbell clean", "db clean", "db cleans", "dumbbell cleans", "db hang clean", "dumbbell hang clean", "db power clean", "dumbbell power clean", "db hang power clean", "dumbbell hang power clean", "db squat clean", "dumbbell squat clean"],
    category: "dumbbell",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "squat"],
    primaryMuscles: ["glutes", "hamstrings", "quads", "traps"],
    secondaryMuscles: ["core", "forearms_grip"],
    equipment: ["dumbbell"],
    measurementType: "reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(2, 1.5, 2.5),
  },
  {
    id: "kettlebell_snatch",
    name: "Kettlebell snatch",
    aliases: ["kettlebell snatch", "kb snatch", "kb snatches"],
    category: "kettlebell",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "vertical_push"],
    primaryMuscles: ["glutes", "hamstrings", "shoulders"],
    secondaryMuscles: ["core", "forearms_grip"],
    equipment: ["kettlebell"],
    measurementType: "reps",
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(1.5, 1.5, 2.5),
  },
  {
    id: "devil_press",
    name: "Devil press",
    aliases: ["devil press", "devil presses", "devils press", "devil's press"],
    category: "dumbbell",
    movementPattern: "olympic_lift",
    secondaryPatterns: ["hinge", "vertical_push", "horizontal_push"],
    primaryMuscles: ["glutes", "hamstrings", "shoulders", "chest"],
    secondaryMuscles: ["core", "triceps", "quads"],
    equipment: ["dumbbell"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 2,
    eccentricLoad: 1,
    cost: c(2, 2, 3),
  },

  // ---------------------------------------------------------------------------
  // Horizontal push
  // ---------------------------------------------------------------------------
  {
    id: "bench_press",
    name: "Bench press",
    aliases: ["bench press", "bench", "bp", "développé couché", "developpe couche", "dc", "flat bench"],
    category: "barbell",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps", "shoulders"],
    equipment: ["barbell", "bench", "rack"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 2,
    isBenchmarkLift: true,
    cost: c(0, 3, 0.5),
  },
  {
    id: "incline_bench_press",
    name: "Incline bench press",
    aliases: ["incline bench press", "incline bench", "développé incliné", "incline press", "incline db press", "incline dumbbell press"],
    category: "barbell",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "shoulders", "triceps"],
    equipment: ["barbell", "dumbbell", "bench"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(0, 2.5, 0.5),
  },
  {
    id: "dumbbell_bench_press",
    name: "Dumbbell bench press",
    aliases: ["dumbbell bench press", "db bench", "db bench press", "dumbbell bench", "développé haltères", "db press flat"],
    category: "dumbbell",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps", "shoulders"],
    equipment: ["dumbbell", "bench"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(0, 2.5, 0.5),
  },
  {
    id: "push_up",
    name: "Push-up",
    aliases: ["push up", "push-up", "push ups", "push-ups", "pushup", "pushups", "pompe", "pompes", "hand release push up", "hr push up", "hrpu", "hand release push-ups"],
    category: "bodyweight",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps", "shoulders"],
    secondaryMuscles: ["core"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 1.5, 1),
  },
  {
    id: "ring_dip",
    name: "Ring dip",
    aliases: ["ring dip", "ring dips", "dips aux anneaux"],
    category: "gymnastics",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps", "shoulders"],
    secondaryMuscles: ["core"],
    equipment: ["rings"],
    measurementType: "reps",
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(0, 2.5, 1),
  },
  {
    id: "dip",
    name: "Dip",
    aliases: ["dip", "dips", "bar dip", "bar dips", "parallel bar dips", "dips barres"],
    category: "bodyweight",
    movementPattern: "horizontal_push",
    primaryMuscles: ["chest", "triceps", "shoulders"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(0, 2, 1),
  },
  {
    id: "burpee",
    name: "Burpee",
    aliases: ["burpee", "burpees", "burpie", "burpies"],
    category: "bodyweight",
    movementPattern: "horizontal_push",
    secondaryPatterns: ["squat", "locomotion"],
    primaryMuscles: ["chest", "quads", "shoulders"],
    secondaryMuscles: ["core", "calves", "glutes"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 2,
    eccentricLoad: 1,
    cost: c(1.5, 1.5, 3),
  },
  {
    id: "bar_facing_burpee",
    name: "Bar-facing burpee",
    aliases: ["bar facing burpee", "bar facing burpees", "bar-facing burpee", "bar-facing burpees", "bfb", "burpee over bar", "burpees over bar", "lateral burpee over bar", "burpee over the bar"],
    category: "bodyweight",
    movementPattern: "horizontal_push",
    secondaryPatterns: ["squat", "locomotion"],
    primaryMuscles: ["chest", "quads", "shoulders"],
    secondaryMuscles: ["core", "calves", "glutes"],
    equipment: ["bodyweight", "barbell"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 3,
    eccentricLoad: 1,
    cost: c(1.5, 1.5, 3),
  },
  {
    id: "burpee_box_jump_over",
    name: "Burpee box jump-over",
    aliases: ["burpee box jump over", "burpee box jump-over", "burpee box jump overs", "bbjo", "burpee box jump", "burpee box jumps"],
    category: "bodyweight",
    movementPattern: "horizontal_push",
    secondaryPatterns: ["squat", "locomotion"],
    primaryMuscles: ["quads", "chest", "glutes", "calves"],
    secondaryMuscles: ["core", "shoulders"],
    equipment: ["bodyweight", "box"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 3,
    eccentricLoad: 2,
    cost: c(2.5, 1.5, 3),
  },

  // ---------------------------------------------------------------------------
  // Vertical push
  // ---------------------------------------------------------------------------
  {
    id: "strict_press",
    name: "Strict press",
    aliases: ["strict press", "shoulder press", "press", "overhead press", "ohp", "military press", "développé militaire", "dm", "barbell press", "strict shoulder press"],
    category: "barbell",
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["core", "traps", "upper_back"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(0, 3, 0.5),
  },
  {
    id: "push_press",
    name: "Push press",
    aliases: ["push press", "push presses", "pp", "développé poussé"],
    category: "barbell",
    movementPattern: "vertical_push",
    secondaryPatterns: ["squat"],
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["quads", "glutes", "core"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(1, 2.5, 1),
  },
  {
    id: "push_jerk",
    name: "Push jerk",
    aliases: ["push jerk", "push jerks", "jerk", "jerks", "jeté"],
    category: "olympic",
    movementPattern: "vertical_push",
    secondaryPatterns: ["squat", "olympic_lift"],
    primaryMuscles: ["shoulders", "triceps", "quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 4,
    impactLevel: 1,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(1.5, 2.5, 1),
  },
  {
    id: "split_jerk",
    name: "Split jerk",
    aliases: ["split jerk", "split jerks", "jeté fente"],
    category: "olympic",
    movementPattern: "vertical_push",
    secondaryPatterns: ["olympic_lift"],
    primaryMuscles: ["shoulders", "triceps", "quads"],
    secondaryMuscles: ["glutes", "core"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 5,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(1.5, 2.5, 1),
  },
  {
    id: "dumbbell_press",
    name: "Dumbbell shoulder press",
    aliases: ["dumbbell shoulder press", "db shoulder press", "db press", "dumbbell press", "db strict press", "dumbbell strict press", "seated db press", "db push press", "dumbbell push press", "presse haltères"],
    category: "dumbbell",
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["core", "traps"],
    equipment: ["dumbbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 2.5, 0.5),
  },
  {
    id: "handstand_push_up",
    name: "Handstand push-up",
    aliases: ["handstand push up", "handstand push-up", "handstand push ups", "handstand push-ups", "hspu", "kipping hspu", "kipping handstand push up", "kipping handstand push-ups"],
    category: "gymnastics",
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["core", "traps"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 4,
    impactLevel: 1,
    eccentricLoad: 2,
    cost: c(0, 3, 1.5),
  },
  {
    id: "strict_handstand_push_up",
    name: "Strict handstand push-up",
    aliases: ["strict handstand push up", "strict handstand push-up", "strict hspu", "shspu", "strict handstand push ups"],
    category: "gymnastics",
    movementPattern: "vertical_push",
    primaryMuscles: ["shoulders", "triceps"],
    secondaryMuscles: ["core", "traps"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 4,
    impactLevel: 0,
    eccentricLoad: 2,
    cost: c(0, 3, 1),
  },
  {
    id: "handstand_walk",
    name: "Handstand walk",
    aliases: ["handstand walk", "hs walk", "hsw", "handstand walking", "marche sur les mains"],
    category: "gymnastics",
    movementPattern: "gymnastics",
    secondaryPatterns: ["vertical_push"],
    primaryMuscles: ["shoulders", "core"],
    secondaryMuscles: ["triceps", "forearms_grip"],
    equipment: ["bodyweight"],
    measurementType: "distance",
    technicalDifficulty: 5,
    impactLevel: 1,
    eccentricLoad: 0,
    cost: c(0, 2, 1.5),
  },
  {
    id: "wall_walk",
    name: "Wall walk",
    aliases: ["wall walk", "wall walks", "ww"],
    category: "gymnastics",
    movementPattern: "gymnastics",
    secondaryPatterns: ["vertical_push"],
    primaryMuscles: ["shoulders", "core"],
    secondaryMuscles: ["triceps", "chest"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0.5, 2.5, 2),
  },
  {
    id: "lateral_raise",
    name: "Lateral raise",
    aliases: ["lateral raise", "lateral raises", "élévations latérales", "side raise", "db lateral raise"],
    category: "dumbbell",
    movementPattern: "isolation",
    primaryMuscles: ["shoulders"],
    equipment: ["dumbbell", "cable"],
    measurementType: "weight_reps",
    defaultIncrementKg: 1,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 1, 0.3),
  },

  // ---------------------------------------------------------------------------
  // Horizontal pull
  // ---------------------------------------------------------------------------
  {
    id: "barbell_row",
    name: "Barbell row",
    aliases: ["barbell row", "bent over row", "bent-over row", "bb row", "rowing barre", "pendlay row", "pendlay rows", "barbell rows", "bent over rows"],
    category: "barbell",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "lower_back", "forearms_grip"],
    equipment: ["barbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0.5, 2.5, 0.5),
  },
  {
    id: "dumbbell_row",
    name: "Dumbbell row",
    aliases: ["dumbbell row", "db row", "db rows", "dumbbell rows", "single arm dumbbell row", "single arm db row", "one arm row", "rowing haltère", "sa db row"],
    category: "dumbbell",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps", "forearms_grip", "core"],
    equipment: ["dumbbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 2.5, 0.5),
  },
  {
    id: "cable_row",
    name: "Cable row",
    aliases: ["cable row", "seated row", "seated cable row", "machine row", "rowing poulie", "tirage horizontal", "chest supported row", "t-bar row"],
    category: "machine",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "forearms_grip"],
    equipment: ["cable", "machine"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 2.5, 0.5),
  },
  {
    id: "ring_row",
    name: "Ring row",
    aliases: ["ring row", "ring rows", "body row", "inverted row", "australian pull up", "australian pull-ups", "tirage anneaux"],
    category: "gymnastics",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["upper_back", "lats"],
    secondaryMuscles: ["biceps", "core"],
    equipment: ["rings"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 2, 1),
  },
  {
    id: "face_pull",
    name: "Face pull",
    aliases: ["face pull", "face pulls", "band pull apart", "band pull aparts", "band pull-aparts"],
    category: "machine",
    movementPattern: "horizontal_pull",
    primaryMuscles: ["upper_back", "shoulders"],
    secondaryMuscles: ["traps"],
    equipment: ["cable"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 0,
    cost: c(0, 1, 0.3),
  },
  {
    id: "biceps_curl",
    name: "Biceps curl",
    aliases: ["biceps curl", "bicep curl", "curl", "curls", "db curl", "dumbbell curl", "barbell curl", "hammer curl", "hammer curls", "curl biceps"],
    category: "dumbbell",
    movementPattern: "isolation",
    primaryMuscles: ["biceps"],
    secondaryMuscles: ["forearms_grip"],
    equipment: ["dumbbell", "barbell", "cable"],
    measurementType: "weight_reps",
    defaultIncrementKg: 1,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 1, 0.3),
  },
  {
    id: "triceps_extension",
    name: "Triceps extension",
    aliases: ["triceps extension", "tricep extension", "triceps extensions", "skull crusher", "skull crushers", "triceps pushdown", "pushdown", "pushdowns", "extension triceps", "overhead triceps extension"],
    category: "dumbbell",
    movementPattern: "isolation",
    primaryMuscles: ["triceps"],
    equipment: ["dumbbell", "barbell", "cable"],
    measurementType: "weight_reps",
    defaultIncrementKg: 1,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 1, 0.3),
  },

  // ---------------------------------------------------------------------------
  // Vertical pull
  // ---------------------------------------------------------------------------
  {
    id: "pull_up",
    name: "Pull-up",
    aliases: ["pull up", "pull-up", "pull ups", "pull-ups", "pullup", "pullups", "pu", "kipping pull up", "kipping pull-ups", "kipping pull ups", "butterfly pull ups", "butterfly pull-ups", "traction", "tractions"],
    category: "gymnastics",
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats", "upper_back", "biceps"],
    secondaryMuscles: ["forearms_grip", "core", "shoulders"],
    equipment: ["pull_up_bar"],
    measurementType: "reps",
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(0, 2.5, 1.5),
  },
  {
    id: "strict_pull_up",
    name: "Strict pull-up",
    aliases: ["strict pull up", "strict pull-up", "strict pull ups", "strict pull-ups", "strict pullups", "tractions strictes", "weighted pull up", "weighted pull-ups", "weighted pull ups", "traction lestée"],
    category: "gymnastics",
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats", "upper_back", "biceps"],
    secondaryMuscles: ["forearms_grip", "core"],
    equipment: ["pull_up_bar"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 2,
    isBenchmarkLift: true,
    cost: c(0, 3, 1),
  },
  {
    id: "chest_to_bar",
    name: "Chest-to-bar pull-up",
    aliases: ["chest to bar", "chest-to-bar", "c2b", "ctb", "chest to bar pull up", "chest to bar pull-ups", "chest-to-bar pull-ups", "chest to bar pull ups"],
    category: "gymnastics",
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats", "upper_back", "biceps"],
    secondaryMuscles: ["forearms_grip", "core", "shoulders"],
    equipment: ["pull_up_bar"],
    measurementType: "reps",
    technicalDifficulty: 4,
    impactLevel: 0,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(0, 3, 2),
  },
  {
    id: "bar_muscle_up",
    name: "Bar muscle-up",
    aliases: ["bar muscle up", "bar muscle-up", "bar muscle ups", "bar muscle-ups", "bmu", "bar mu"],
    category: "gymnastics",
    movementPattern: "vertical_pull",
    secondaryPatterns: ["horizontal_push", "gymnastics"],
    primaryMuscles: ["lats", "upper_back", "chest", "triceps"],
    secondaryMuscles: ["forearms_grip", "core", "shoulders", "biceps"],
    equipment: ["pull_up_bar"],
    measurementType: "reps",
    technicalDifficulty: 5,
    impactLevel: 1,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(0, 3, 2),
  },
  {
    id: "ring_muscle_up",
    name: "Ring muscle-up",
    aliases: ["ring muscle up", "ring muscle-up", "ring muscle ups", "ring muscle-ups", "rmu", "muscle up", "muscle-up", "muscle ups", "muscle-ups", "mu"],
    category: "gymnastics",
    movementPattern: "vertical_pull",
    secondaryPatterns: ["horizontal_push", "gymnastics"],
    primaryMuscles: ["lats", "upper_back", "chest", "triceps"],
    secondaryMuscles: ["forearms_grip", "core", "shoulders", "biceps"],
    equipment: ["rings"],
    measurementType: "reps",
    technicalDifficulty: 5,
    impactLevel: 0,
    eccentricLoad: 2,
    isBenchmarkLift: true,
    cost: c(0, 3, 2),
  },
  {
    id: "lat_pulldown",
    name: "Lat pulldown",
    aliases: ["lat pulldown", "lat pull down", "pulldown", "tirage vertical", "tirage poitrine", "lat pulldowns"],
    category: "machine",
    movementPattern: "vertical_pull",
    primaryMuscles: ["lats", "upper_back"],
    secondaryMuscles: ["biceps", "forearms_grip"],
    equipment: ["cable", "machine"],
    measurementType: "weight_reps",
    defaultIncrementKg: 2.5,
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0, 2.5, 0.5),
  },
  {
    id: "rope_climb",
    name: "Rope climb",
    aliases: ["rope climb", "rope climbs", "montée de corde", "montées de corde", "corde"],
    category: "gymnastics",
    movementPattern: "vertical_pull",
    secondaryPatterns: ["gymnastics"],
    primaryMuscles: ["lats", "biceps", "forearms_grip"],
    secondaryMuscles: ["core", "upper_back", "hip_flexors"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 3,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(0.5, 3, 2),
  },
  {
    id: "legless_rope_climb",
    name: "Legless rope climb",
    aliases: ["legless rope climb", "legless rope climbs", "legless", "corde sans jambes"],
    category: "gymnastics",
    movementPattern: "vertical_pull",
    secondaryPatterns: ["gymnastics"],
    primaryMuscles: ["lats", "biceps", "forearms_grip"],
    secondaryMuscles: ["core", "upper_back"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 5,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(0, 3, 2.5),
  },

  // ---------------------------------------------------------------------------
  // Core / gymnastics accessories
  // ---------------------------------------------------------------------------
  {
    id: "toes_to_bar",
    name: "Toes-to-bar",
    aliases: ["toes to bar", "toes-to-bar", "t2b", "ttb", "toe to bar", "toes 2 bar"],
    category: "gymnastics",
    movementPattern: "rotation_core",
    secondaryPatterns: ["gymnastics"],
    primaryMuscles: ["core", "hip_flexors", "lats"],
    secondaryMuscles: ["forearms_grip", "shoulders"],
    equipment: ["pull_up_bar"],
    measurementType: "reps",
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(0.5, 1.5, 2),
  },
  {
    id: "knees_to_elbows",
    name: "Knees-to-elbows",
    aliases: ["knees to elbows", "knees-to-elbows", "k2e", "kte", "knee raise", "hanging knee raise", "hanging knee raises", "knee raises"],
    category: "gymnastics",
    movementPattern: "rotation_core",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["forearms_grip", "lats"],
    equipment: ["pull_up_bar"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0.5, 1, 1.5),
  },
  {
    id: "sit_up",
    name: "Sit-up",
    aliases: ["sit up", "sit-up", "sit ups", "sit-ups", "situp", "situps", "abmat sit up", "abmat sit-ups", "abmat situps", "abdos"],
    category: "bodyweight",
    movementPattern: "rotation_core",
    primaryMuscles: ["core", "hip_flexors"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0.5, 0.5, 1),
  },
  {
    id: "ghd_sit_up",
    name: "GHD sit-up",
    aliases: ["ghd sit up", "ghd sit-up", "ghd sit ups", "ghd sit-ups", "ghd", "ghdsu"],
    category: "bodyweight",
    movementPattern: "rotation_core",
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["quads"],
    equipment: ["ghd"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 3,
    cost: c(1, 0.5, 1.5),
  },
  {
    id: "v_up",
    name: "V-up",
    aliases: ["v up", "v-up", "v ups", "v-ups", "vup", "vups"],
    category: "bodyweight",
    movementPattern: "rotation_core",
    primaryMuscles: ["core", "hip_flexors"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(0.5, 0.5, 1),
  },
  {
    id: "hollow_rock",
    name: "Hollow rock",
    aliases: ["hollow rock", "hollow rocks", "hollow hold", "hollow body", "hollow"],
    category: "gymnastics",
    movementPattern: "rotation_core",
    primaryMuscles: ["core", "hip_flexors"],
    equipment: ["bodyweight"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 0,
    cost: c(0.3, 0.5, 1),
  },
  {
    id: "plank",
    name: "Plank",
    aliases: ["plank", "planks", "planche", "gainage", "front plank", "side plank"],
    category: "bodyweight",
    movementPattern: "rotation_core",
    primaryMuscles: ["core"],
    secondaryMuscles: ["shoulders"],
    equipment: ["bodyweight"],
    measurementType: "time",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 0,
    cost: c(0.2, 0.5, 0.5),
  },
  {
    id: "l_sit",
    name: "L-sit",
    aliases: ["l sit", "l-sit", "l sits", "l-sits", "lsit"],
    category: "gymnastics",
    movementPattern: "rotation_core",
    secondaryPatterns: ["gymnastics"],
    primaryMuscles: ["core", "hip_flexors"],
    secondaryMuscles: ["triceps", "shoulders", "quads"],
    equipment: ["bodyweight", "rings"],
    measurementType: "time",
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 0,
    cost: c(0.5, 1, 0.5),
  },
  {
    id: "turkish_get_up",
    name: "Turkish get-up",
    aliases: ["turkish get up", "turkish get-up", "tgu", "get up", "get-up", "turkish get ups"],
    category: "kettlebell",
    movementPattern: "rotation_core",
    secondaryPatterns: ["vertical_push", "squat"],
    primaryMuscles: ["core", "shoulders", "glutes"],
    secondaryMuscles: ["quads", "triceps"],
    equipment: ["kettlebell", "dumbbell"],
    measurementType: "weight_reps",
    defaultIncrementKg: 4,
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 1,
    cost: c(1, 1.5, 1),
  },

  // ---------------------------------------------------------------------------
  // Carry
  // ---------------------------------------------------------------------------
  {
    id: "farmer_carry",
    name: "Farmer carry",
    aliases: ["farmer carry", "farmers carry", "farmer's carry", "farmer walk", "farmers walk", "farmer's walk", "kb carry", "db carry", "dumbbell carry", "kettlebell carry", "farmer"],
    category: "strongman",
    movementPattern: "carry",
    secondaryPatterns: ["locomotion"],
    primaryMuscles: ["forearms_grip", "traps", "core"],
    secondaryMuscles: ["quads", "glutes", "calves", "upper_back"],
    equipment: ["dumbbell", "kettlebell"],
    measurementType: "distance",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 0,
    cost: c(1, 1.5, 1.5),
  },
  {
    id: "front_rack_carry",
    name: "Front rack carry",
    aliases: ["front rack carry", "front rack walk", "double kb front rack carry", "front rack kb carry", "front rack lunge walk"],
    category: "strongman",
    movementPattern: "carry",
    secondaryPatterns: ["locomotion"],
    primaryMuscles: ["core", "upper_back", "shoulders"],
    secondaryMuscles: ["quads", "glutes", "forearms_grip"],
    equipment: ["kettlebell", "dumbbell"],
    measurementType: "distance",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 0,
    cost: c(1, 1.5, 1.5),
  },
  {
    id: "overhead_carry",
    name: "Overhead carry",
    aliases: ["overhead carry", "oh carry", "overhead walk", "waiter carry", "waiter walk", "ohc"],
    category: "strongman",
    movementPattern: "carry",
    secondaryPatterns: ["locomotion", "vertical_push"],
    primaryMuscles: ["shoulders", "core", "traps"],
    secondaryMuscles: ["triceps", "upper_back"],
    equipment: ["kettlebell", "dumbbell", "barbell"],
    measurementType: "distance",
    technicalDifficulty: 2,
    impactLevel: 1,
    eccentricLoad: 0,
    cost: c(0.5, 2, 1.5),
  },
  {
    id: "sandbag_carry",
    name: "Sandbag carry",
    aliases: ["sandbag carry", "sandbag carries", "sandbag walk", "bear hug carry", "sandbag run", "sandbag lunge", "sandbag lunges"],
    category: "strongman",
    movementPattern: "carry",
    secondaryPatterns: ["locomotion"],
    primaryMuscles: ["core", "upper_back", "quads", "glutes"],
    secondaryMuscles: ["forearms_grip", "biceps", "calves"],
    equipment: ["sandbag"],
    measurementType: "distance",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(2, 1.5, 2.5),
  },
  {
    id: "sandbag_clean",
    name: "Sandbag clean",
    aliases: ["sandbag clean", "sandbag cleans", "sandbag to shoulder", "sandbag over shoulder", "d-ball over shoulder", "d ball over shoulder", "dball", "d-ball", "d ball", "sandbag ground to shoulder"],
    category: "strongman",
    movementPattern: "hinge",
    secondaryPatterns: ["olympic_lift", "squat"],
    primaryMuscles: ["glutes", "hamstrings", "quads", "upper_back"],
    secondaryMuscles: ["biceps", "core", "forearms_grip", "lower_back"],
    equipment: ["sandbag"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 1,
    eccentricLoad: 1,
    cost: c(2.5, 2, 2.5),
  },
  {
    id: "sled_push",
    name: "Sled push",
    aliases: ["sled push", "sled pushes", "prowler push", "prowler", "sled", "poussée de sled", "pousser le sled"],
    category: "strongman",
    movementPattern: "locomotion",
    secondaryPatterns: ["squat", "horizontal_push"],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["core", "shoulders", "triceps"],
    equipment: ["sled"],
    measurementType: "distance",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 0,
    cost: c(2.5, 1, 3),
  },
  {
    id: "sled_pull",
    name: "Sled pull",
    aliases: ["sled pull", "sled pulls", "sled drag", "sled drags", "rope sled pull", "tirage de sled"],
    category: "strongman",
    movementPattern: "horizontal_pull",
    secondaryPatterns: ["locomotion", "hinge"],
    primaryMuscles: ["upper_back", "lats", "hamstrings", "glutes"],
    secondaryMuscles: ["biceps", "forearms_grip", "core"],
    equipment: ["sled"],
    measurementType: "distance",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 0,
    cost: c(2, 2, 3),
  },

  // ---------------------------------------------------------------------------
  // Plyometric / locomotion
  // ---------------------------------------------------------------------------
  {
    id: "box_jump",
    name: "Box jump",
    aliases: ["box jump", "box jumps", "bj", "saut de box", "sauts sur box", "box jump 24", "box jump 30"],
    category: "bodyweight",
    movementPattern: "squat",
    secondaryPatterns: ["locomotion"],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["box"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 3,
    eccentricLoad: 2,
    cost: c(2, 0, 2),
  },
  {
    id: "box_jump_over",
    name: "Box jump-over",
    aliases: ["box jump over", "box jump-over", "box jump overs", "box jump-overs", "bjo", "box over", "box overs"],
    category: "bodyweight",
    movementPattern: "squat",
    secondaryPatterns: ["locomotion"],
    primaryMuscles: ["quads", "glutes", "calves"],
    secondaryMuscles: ["hamstrings", "core"],
    equipment: ["box"],
    measurementType: "reps",
    technicalDifficulty: 2,
    impactLevel: 3,
    eccentricLoad: 2,
    cost: c(2, 0, 2.5),
  },
  {
    id: "double_under",
    name: "Double-under",
    aliases: ["double under", "double-under", "double unders", "double-unders", "du", "dus", "dubs", "corde à sauter double", "doubles"],
    category: "monostructural",
    movementPattern: "locomotion",
    primaryMuscles: ["calves"],
    secondaryMuscles: ["shoulders", "forearms_grip", "core", "quads"],
    equipment: ["jump_rope"],
    measurementType: "reps",
    technicalDifficulty: 3,
    impactLevel: 3,
    eccentricLoad: 1,
    isBenchmarkLift: true,
    cost: c(0.6, 0.3, 1.5),
  },
  {
    id: "single_under",
    name: "Single-under",
    aliases: ["single under", "single-under", "single unders", "single-unders", "su", "sus", "singles", "corde à sauter", "jump rope"],
    category: "monostructural",
    movementPattern: "locomotion",
    primaryMuscles: ["calves"],
    secondaryMuscles: ["shoulders", "forearms_grip"],
    equipment: ["jump_rope"],
    measurementType: "reps",
    technicalDifficulty: 1,
    impactLevel: 2,
    eccentricLoad: 0,
    cost: c(0.3, 0.1, 0.8),
  },
  {
    id: "run",
    name: "Run",
    aliases: ["run", "runs", "running", "course", "courir", "cap", "footing", "jog", "jogging", "sprint", "sprints", "shuttle run", "shuttle runs", "200m run", "400m run", "800m run"],
    category: "monostructural",
    movementPattern: "locomotion",
    primaryMuscles: ["quads", "hamstrings", "glutes", "calves"],
    secondaryMuscles: ["hip_flexors", "core"],
    equipment: ["outdoor", "treadmill", "track"],
    measurementType: "distance",
    technicalDifficulty: 1,
    impactLevel: 3,
    eccentricLoad: 2,
    modality: "running",
    cost: c(1.5, 0, 3),
  },
  {
    id: "row",
    name: "Row (erg)",
    aliases: ["row", "rowing", "rower", "rameur", "erg", "c2", "concept2", "concept 2", "row erg", "rowerg", "cal row", "row cal", "row calories", "calorie row", "calories row", "m row", "row m", "meter row", "metre row"],
    category: "monostructural",
    movementPattern: "locomotion",
    secondaryPatterns: ["horizontal_pull", "hinge"],
    primaryMuscles: ["quads", "glutes", "upper_back", "lats"],
    secondaryMuscles: ["hamstrings", "core", "biceps", "forearms_grip"],
    equipment: ["rower"],
    measurementType: "distance",
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 0,
    modality: "row",
    cost: c(1.5, 1, 3),
  },
  {
    id: "bike_erg",
    name: "BikeErg",
    aliases: ["bike erg", "bikeerg", "bike", "vélo", "velo", "c2 bike", "concept2 bike", "cal bike", "bike cal", "bike calories", "calorie bike", "calories bike"],
    category: "monostructural",
    movementPattern: "locomotion",
    primaryMuscles: ["quads", "glutes"],
    secondaryMuscles: ["hamstrings", "calves"],
    equipment: ["bike_erg"],
    measurementType: "calories",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 0,
    modality: "bike",
    cost: c(1.5, 0, 3),
  },
  {
    id: "assault_bike",
    name: "Assault bike",
    aliases: ["assault bike", "assaultbike", "echo bike", "air bike", "airbike", "ab", "cal assault", "assault cal", "assault bike calories", "echo bike calories", "cal echo", "echo cal", "rogue echo", "air bike calories", "cal ab"],
    category: "monostructural",
    movementPattern: "locomotion",
    secondaryPatterns: ["horizontal_push", "horizontal_pull"],
    primaryMuscles: ["quads", "glutes", "shoulders", "upper_back"],
    secondaryMuscles: ["hamstrings", "chest", "core"],
    equipment: ["assault_bike"],
    measurementType: "calories",
    technicalDifficulty: 1,
    impactLevel: 0,
    eccentricLoad: 0,
    modality: "bike",
    cost: c(1.5, 1, 3),
  },
  {
    id: "ski_erg",
    name: "SkiErg",
    aliases: ["ski erg", "skierg", "ski", "skiing", "cal ski", "ski cal", "ski calories", "calorie ski", "m ski", "ski m", "meter ski"],
    category: "monostructural",
    movementPattern: "locomotion",
    secondaryPatterns: ["vertical_pull", "hinge", "rotation_core"],
    primaryMuscles: ["lats", "triceps", "core"],
    secondaryMuscles: ["shoulders", "hamstrings", "glutes"],
    equipment: ["ski_erg"],
    measurementType: "distance",
    technicalDifficulty: 2,
    impactLevel: 0,
    eccentricLoad: 0,
    modality: "ski",
    cost: c(0.5, 2, 3),
  },
  {
    id: "swim",
    name: "Swim",
    aliases: ["swim", "swimming", "nage", "natation", "nager"],
    category: "monostructural",
    movementPattern: "locomotion",
    secondaryPatterns: ["horizontal_pull"],
    primaryMuscles: ["lats", "shoulders", "core"],
    secondaryMuscles: ["triceps", "quads", "glutes"],
    equipment: ["pool"],
    measurementType: "distance",
    technicalDifficulty: 3,
    impactLevel: 0,
    eccentricLoad: 0,
    modality: "swimming",
    cost: c(0.5, 1.5, 3),
  },
  {
    id: "walk",
    name: "Walk",
    aliases: ["walk", "walking", "marche", "marcher", "hike", "hiking", "randonnée", "rando"],
    category: "monostructural",
    movementPattern: "locomotion",
    primaryMuscles: ["calves", "glutes", "quads"],
    equipment: ["outdoor"],
    measurementType: "distance",
    technicalDifficulty: 1,
    impactLevel: 1,
    eccentricLoad: 0,
    modality: "walking",
    cost: c(0.5, 0, 1),
  },
];

const byId = new Map<string, ExerciseDef>(EXERCISE_CATALOG.map((e) => [e.id, e]));

export function getExercise(id: string): ExerciseDef | undefined {
  return byId.get(id);
}

export function requireExercise(id: string): ExerciseDef {
  const e = byId.get(id);
  if (!e) throw new Error(`Unknown exercise id: ${id}`);
  return e;
}

export const BENCHMARK_LIFT_IDS: readonly string[] = EXERCISE_CATALOG.filter(
  (e) => e.isBenchmarkLift,
).map((e) => e.id);
